### ISSUE TITLE
Avoid hitting slurm limits for maximum job count / array size

### ISSUE THREAD

**Issue by philippotto** [scalableminds/cluster_tools#104]
When trying to schedule too many tasks, slurm's config can make the submission fail. To avoid the limits, the tasks can be chunked accordingly.

See https://github.com/scalableminds/cluster_tools/pull/103 for a reference of implementation.

**Comment by normanrz** [comment]
I also ran into this issue. Would probably make sense to have the limit detected automatically. Here is a sample bash command:
```bash
scontrol show config | sed -n '/^MaxArraySize/s/.*= *//p'
```
(from https://unix.stackexchange.com/questions/364612/how-to-check-slurm-environmental-variables-programmatically)
