### ISSUE TITLE
Restart Failed Jobs

### ISSUE THREAD

**Issue by georgwiese** [scalableminds/cluster_tools#8]
We've experienced that on some clusters, the jobs might fail in a way that simply retrying them would help. For example, some nodes might not have the necessary libraries installed and restarting would likely schedule the job on a healthy node.

There are Slurm primitives to implement this (Manuel is currently implementing that on the Matlab Pipeline).

**Comment by manuel-berning** [comment]
I mentioned it when I was visiting two weeks ago as a possible solution to error in single jobs (e.g. missing library) in a job array. I have not started implementing anything so I cannot say whether it will work. Sources This is what I looked at back then:
If you search for requeue here:
https://slurm.schedmd.com/sbatch.html
and this section in general
https://slurm.schedmd.com/nonstop.html
But can not yet say whether either of this is a good solution.

**Comment by philippotto** [comment]
I don't think this issue is necessary right now. Let's reopen it when it becomes important.
