### ISSUE TITLE
add executor that uses a for-loop

### ISSUE THREAD

**Issue by jstriebel** [scalableminds/cluster_tools#99]
It would be great to have an executor (e.g. `DebugExecutor`) that just wraps a normal for-loop. This should only be used for debugging purposes, but it would be very helpful in such cases. One use case is e.g. when running tests, [dropping into pdb](https://docs.pytest.org/en/6.2.x/usage.html#dropping-to-pdb-python-debugger-on-failures) is not possible in futures, the resulting shell is in the context of the caller then.

**Comment by philippotto** [comment]
Fixed by #102.
